{{/*
Expand the name of the chart.
*/}}
{{- define "ai-edge.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "ai-edge.fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "ai-edge.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels.
*/}}
{{- define "ai-edge.labels" -}}
helm.sh/chart: {{ include "ai-edge.chart" . }}
{{ include "ai-edge.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels.
*/}}
{{- define "ai-edge.selectorLabels" -}}
app.kubernetes.io/name: {{ include "ai-edge.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Image full name with tag.
If the repository already includes a registry (contains "/"),
global.imageRegistry is NOT prepended to avoid duplication.
*/}}
{{- define "ai-edge.image" -}}
{{- $globalReg := .root.Values.global.imageRegistry | default "" }}
{{- $repository := .image.repository }}
{{- $tag := .image.tag | default .root.Chart.AppVersion | toString }}
{{- if and $globalReg (not (contains "/" $repository)) }}
{{- printf "%s/%s:%s" $globalReg $repository $tag }}
{{- else if contains "/" $repository }}
{{- printf "%s:%s" $repository $tag }}
{{- else }}
{{- printf "%s:%s" $repository $tag }}
{{- end }}
{{- end }}

{{/*
DB host resolution:
  - if db.host is set, use it directly (external DB)
  - if postgresql.enabled, use the in-chart postgres FQDN
  - otherwise empty (must be provided)
*/}}
{{- define "ai-edge.dbHost" -}}
{{- if .Values.db.host }}
{{- .Values.db.host }}
{{- else if .Values.postgresql.enabled }}
{{- printf "%s-postgresql.%s.svc.cluster.local" .Release.Name .Release.Namespace }}
{{- else }}
{{- printf "" }}
{{- end }}
{{- end }}

{{/*
MinIO host resolution.
*/}}
{{- define "ai-edge.minioHost" -}}
{{- if .Values.minio.externalHost }}
{{- .Values.minio.externalHost }}
{{- else if .Values.minio.enabled }}
{{- printf "%s-minio.%s.svc.cluster.local" .Release.Name .Release.Namespace }}
{{- else }}
{{- printf "" }}
{{- end }}
{{- end }}

{{/*
Resolve the storageClass to use for a component's PVC.

Priority (highest first):
  1. <component>.persistence.storageClass  (component-specific override)
  2. global.storageClass                   (cluster-wide default)
  3. ""                                     (let the cluster pick its default SC)

Usage:
  include "ai-edge.storageClass" (dict "root" . "component" "postgresql")
  include "ai-edge.storageClass" (dict "root" . "storageClass" .Values.postgresql.persistence.storageClass)
*/}}
{{- define "ai-edge.storageClass" -}}
{{- $componentSc := "" -}}
{{- if .component -}}
  {{- $componentSc = index .root.Values .component "persistence" "storageClass" | default "" -}}
{{- else -}}
  {{- $componentSc = .storageClass | default "" -}}
{{- end -}}
{{- if $componentSc -}}
{{- $componentSc -}}
{{- else if .root.Values.global.storageClass -}}
{{- .root.Values.global.storageClass -}}
{{- end -}}
{{- end -}}

{{/*
Persistence volume claim spec helper.
*/}}
{{- define "ai-edge.pvc" -}}
{{- $storageClass := include "ai-edge.storageClass" (dict "root" .root "component" .component "storageClass" .storageClass) -}}
{{- if $storageClass }}
storageClassName: {{ $storageClass }}
{{- end }}
resources:
  requests:
    storage: {{ .size | quote }}
{{- end }}

{{/*
Resolve the Secret name that holds DB credentials consumed by
apiserver / controller / gateway-runtime.

Precedence (highest first):
  1. .Values.db.existingSecret
  2. .Values.db.secretName (auto-generated by the chart when
     .Values.db.createSecret is true)
  3. "" — caller decides whether to skip the env entry.
*/}}
{{- define "ai-edge.dbSecretName" -}}
{{- if .Values.db.existingSecret -}}
{{- .Values.db.existingSecret -}}
{{- else -}}
{{- .Values.db.secretName -}}
{{- end -}}
{{- end -}}

{{/*
DB username resolution. Prefers the secret key `username` when an
existing secret is referenced, otherwise the chart's configured value.
Because Helm templates cannot read the secret's contents at render
time, the deployments always use the same chart-level username.
The `username` key is only honored by the auto-generated secret.
*/}}
{{- define "ai-edge.dbUsername" -}}
{{- .Values.db.username -}}
{{- end -}}

{{/*
DB password resolution. Returns the literal value from .Values.db.password
when the user has set one; otherwise returns the empty string and lets the
caller wire a `secretKeyRef`. The actual secret data is materialised by
the `secrets.yaml` template.
*/}}
{{- define "ai-edge.dbPassword" -}}
{{- if .Values.db.existingSecret -}}
{{- "" -}}
{{- else if .Values.db.password -}}
{{- .Values.db.password -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end -}}

{{/*
Resolve the Secret name the bundled PostgreSQL pod reads POSTGRES_PASSWORD
from.

Precedence (highest first):
  1. .Values.postgresql.auth.existingSecret — the operator pre-created
     a Secret with the desired PG password (e.g. for an externally
     managed Postgres that still lives behind this chart's PG pod).
  2. ai-edge.dbSecretName — the chart's own `edgeai-db` Secret, shared
     with apiserver / controller / gateway. This is the default when
     the chart owns the database end-to-end.
*/}}
{{- define "ai-edge.postgresPasswordSecretName" -}}
{{- if .Values.postgresql.auth.existingSecret -}}
{{- .Values.postgresql.auth.existingSecret -}}
{{- else -}}
{{- include "ai-edge.dbSecretName" . -}}
{{- end -}}
{{- end -}}

{{/*
Resolve the Secret name for the chart's bundled PostgreSQL.

Precedence (highest first):
  1. .Values.postgresql.auth.existingSecret
  2. "" (empty) — the bundled PostgreSQL no longer owns a dedicated
     secret; it reads its password from `edgeai-db` (db.secretName) so
     the apiserver / controller / gateway and the database always see
     the same value. This helper is kept for backward compatibility
     (e.g. external tooling that still references it) but always
     resolves to the empty string in the chart's own templates.
*/}}
{{- define "ai-edge.postgresqlSecretName" -}}
{{- if .Values.postgresql.auth.existingSecret -}}
{{- .Values.postgresql.auth.existingSecret -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end -}}

{{/*
Resolve the Secret name for the chart's bundled MinIO.

Precedence (highest first):
  1. .Values.minio.auth.existingSecret
  2. <release-name>-minio-secret (auto-generated by the chart)
*/}}
{{- define "ai-edge.minioSecretName" -}}
{{- if .Values.minio.auth.existingSecret -}}
{{- .Values.minio.auth.existingSecret -}}
{{- else -}}
{{- printf "%s-minio-secret" .Release.Name -}}
{{- end -}}
{{- end -}}

{{/*
apiserver CA Secret name resolution.

Precedence (highest first):
  1. .Values.apiserver.ca.existingSecret
  2. <fullname>-apiserver-ca (auto-generated by the chart when
     .Values.apiserver.ca.generate is true)
  3. .Values.apiserver.ca.secretName (override; empty when none)
*/}}
{{- define "ai-edge.apiserverCaSecretName" -}}
{{- if .Values.apiserver.ca.existingSecret -}}
{{- .Values.apiserver.ca.existingSecret -}}
{{- else if .Values.apiserver.ca.generate -}}
{{- printf "%s-apiserver-ca" (include "ai-edge.fullname" .) -}}
{{- else if .Values.apiserver.ca.secretName -}}
{{- .Values.apiserver.ca.secretName -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end -}}

{{/*
gateway-runtime TLS server-cert Secret name resolution.

Precedence (highest first):
  1. .Values.gatewayRuntime.tls.existingSecret
  2. <fullname>-gateway-tls (auto-generated by the chart when
     .Values.gatewayRuntime.tls.generate is true)
  3. .Values.gatewayRuntime.tls.secretName (override; empty when none)
*/}}
{{- define "ai-edge.gatewayTlsSecretName" -}}
{{- if .Values.gatewayRuntime.tls.existingSecret -}}
{{- .Values.gatewayRuntime.tls.existingSecret -}}
{{- else if .Values.gatewayRuntime.tls.generate -}}
{{- printf "%s-gateway-tls" (include "ai-edge.fullname" .) -}}
{{- else if .Values.gatewayRuntime.tls.secretName -}}
{{- .Values.gatewayRuntime.tls.secretName -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end -}}

{{/*
gateway-runtime CA bundle Secret name resolution. Same precedence as the
apiserver CA helper but reads from .Values.gatewayRuntime.ca.
*/}}
{{- define "ai-edge.gatewayCaSecretName" -}}
{{- if .Values.gatewayRuntime.ca.existingSecret -}}
{{- .Values.gatewayRuntime.ca.existingSecret -}}
{{- else if .Values.gatewayRuntime.ca.generate -}}
{{- printf "%s-gateway-ca" (include "ai-edge.fullname" .) -}}
{{- else if .Values.gatewayRuntime.ca.secretName -}}
{{- .Values.gatewayRuntime.ca.secretName -}}
{{- else -}}
{{- "" -}}
{{- end -}}
{{- end -}}

{{/*
Whether the chart should auto-generate the bundled DB Secret.

Resolution:
  - .Values.db.createSecret=true → yes
  - .Values.postgresql.enabled=true → yes (we own the DB and must publish
    the password somewhere the control-plane pods can read)
  - otherwise → no (external DB: user owns the secret)
*/}}
{{- define "ai-edge.dbCreateSecret" -}}
{{- if .Values.db.createSecret -}}
{{- true -}}
{{- else if .Values.postgresql.enabled -}}
{{- true -}}
{{- else -}}
{{- false -}}
{{- end -}}
{{- end -}}
